Telecominfraproject/wlan-cloud-rrm

src/main/java/com/facebook/openwifirrm/modules/ConfigManager.java
src/main/java/com/facebook/openwifirrm/modules/DataCollector.java

Fix typo in module init loops

---

Dockerfile
helm/templates/pvc.yaml
helm/values.yaml

Signed-off-by: Johann Hoffmann <johann.hoffmann@mailbox.org>

[WIFI-10387] Adapt rrm service configuration for successful integration into Docker Compose deployment

---

src/main/java/com/facebook/openwifirrm/Constants.java
src/main/java/com/facebook/openwifirrm/optimizers/ChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/optimizers/LeastUsedChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/optimizers/LocationBasedOptimalTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/MeasurementBasedApApTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/MeasurementBasedApClientTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/RandomTxPowerInitializer.java
src/main/java/com/facebook/openwifirrm/optimizers/TPC.java
src/main/java/com/facebook/openwifirrm/optimizers/UnmanagedApAwareChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralConstants.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralUtils.java
src/test/java/com/facebook/openwifirrm/DeviceConfigTest.java
src/test/java/com/facebook/openwifirrm/DeviceDataManagerTest.java
src/test/java/com/facebook/openwifirrm/modules/ApiServerTest.java
src/test/java/com/facebook/openwifirrm/optimizers/LeastUsedChannelOptimizerTest.java
src/test/java/com/facebook/openwifirrm/optimizers/LocationBasedOptimalTPCTest.java
src/test/java/com/facebook/openwifirrm/optimizers/MeasurementBasedApApTPCTest.java
src/test/java/com/facebook/openwifirrm/optimizers/MeasurementBasedApClientTPCTest.java
src/test/java/com/facebook/openwifirrm/optimizers/RandomChannelInitializerTest.java
src/test/java/com/facebook/openwifirrm/optimizers/RandomTxPowerInitializerTest.java
src/test/java/com/facebook/openwifirrm/optimizers/TestUtils.java
src/test/java/com/facebook/openwifirrm/optimizers/UnmanagedApAwareChannelOptimizerTest.java

- Move BAND_2G and BAND_5G into a new Consts class
- Add comments to some fields of WifiScanEntry

Refactor constants and add code comments

---

src/main/java/com/facebook/openwifirrm/aggregators/Aggregator.java
src/main/java/com/facebook/openwifirrm/mysql/DatabaseManager.java

Fix javadoc build error/warning introduced in #25: https://github.com/Telecominfraproject/wlan-cloud-rrm/runs/7889646388?check_suite_focus=true

Fix javadoc errors from #25

---

src/main/java/com/facebook/openwifirrm/optimizers/channel/ChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/ucentral/operationelement/HTOperationElement.java
src/main/java/com/facebook/openwifirrm/ucentral/operationelement/VHTOperationElement.java
src/test/java/com/facebook/openwifirrm/ucentral/operationelement/VHTOperationElementTest.java

Use HTOperationElement and VHTOperationElement instead of other code to decode.

Use ht operation element class decoder

---

src/main/java/com/facebook/openwifirrm/optimizers/channel/ChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/LeastUsedChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/LocationBasedOptimalTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/TPC.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralConstants.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralUtils.java
src/test/java/com/facebook/openwifirrm/optimizers/TestUtils.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPCTest.java

Enable Measured-based AP-AP TPC in the 2G band and add unit tests for it.

Multi band for MeasurementBasedApApTPC

---

ALGORITHMS.md
IMPLEMENTATION.md
README.md

Minor docs updates to add a bit more context.

Update README and other docs

---

src/main/java/com/facebook/openwifirrm/optimizers/channel/ChannelOptimizer.java

This is a small PR that replaces some code with calls to `UCentralUtils.isChannelInBand()` (which already existed)

Use UCentralUtils.isChannelInBand()

---

IMPLEMENTATION.md
src/main/java/com/facebook/openwifirrm/RRMConfig.java
src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
src/test/java/com/facebook/openwifirrm/modules/ApiServerTest.java

Basic auth is no longer used. Remove it.

remove basic auth

---

pom.xml

Update Spark server to 2.9.4

---

src/main/java/com/facebook/openwifirrm/optimizers/channel/ChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/LeastUsedChannelOptimizer.java

Minor cleanup in channel optimizer

Minor cleanup in channel optimizer

---

src/main/java/com/facebook/openwifirrm/RRMConfig.java

- `DataCollector` loop interval 5sec -> 30sec
- `ConfigManager` loop interval 1min -> 2min

Bump default event loop timers

---

src/main/java/com/facebook/openwifirrm/optimizers/tpc/TPC.java

Updated some comments and removed some unused imports

Minor cleanup in TPC classes

---

src/main/java/com/facebook/openwifirrm/mysql/DatabaseManager.java
src/main/java/com/facebook/openwifirrm/ucentral/models/State.java
src/main/java/com/facebook/openwifirrm/ucentral/prov/models/DeviceConfiguration.java
src/main/java/com/facebook/openwifirrm/ucentral/prov/models/RRMDetails.java
src/test/java/com/facebook/openwifirrm/optimizers/TestUtils.java

Make some inner classes, especially on ones that are just meant to hold data, static. This makes more sense as there should be no relationship between inner and outer class in plain old data structures.

Make inner classes static as necessary

---

src/main/java/com/facebook/openwifirrm/modules/Modeler.java
src/main/java/com/facebook/openwifirrm/mysql/DatabaseManager.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/ChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/LeastUsedChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/RandomChannelInitializer.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApClientTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/TPC.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralUtils.java
src/main/java/com/facebook/openwifirrm/ucentral/models/State.java
src/test/java/com/facebook/openwifirrm/optimizers/TestUtils.java
src/test/java/com/facebook/openwifirrm/optimizers/channel/LeastUsedChannelOptimizerTest.java
src/test/java/com/facebook/openwifirrm/optimizers/channel/RandomChannelInitializerTest.java
src/test/java/com/facebook/openwifirrm/optimizers/channel/UnmanagedApAwareChannelOptimizerTest.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/LocationBasedOptimalTPCTest.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPCTest.java

Cherry pick #76 into release/v2.7.0 to address bugs in AP-AP TPC algorithm.

[WIFI-10805] Make AP-AP TPC algorithm use tx power from statistics and fix TPC application to correct band (#76)

---

src/main/java/com/facebook/openwifirrm/RRMAlgorithm.java
src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
src/main/java/com/facebook/openwifirrm/modules/ConfigManager.java
src/main/java/com/facebook/openwifirrm/modules/RRMScheduler.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/ChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/TPC.java
src/main/java/com/facebook/openwifirrm/ucentral/gw/models/DeviceWithStatus.java

Only push updates for desired zones/venues

Only push updates for desired zones/venues

---

src/main/java/com/facebook/openwifirrm/ucentral/InformationElements.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralUtils.java
src/main/java/com/facebook/openwifirrm/ucentral/WifiScanEntry.java
src/main/java/com/facebook/openwifirrm/ucentral/informationelement/Country.java
src/main/java/com/facebook/openwifirrm/ucentral/informationelement/QbssLoad.java

- Use InformationElements wrapper class
- Catch Exception for parsing errors instead of NullPointerException
- Add/edit javadocs

Refactor IE parsing

---

helm/values.yaml

Signed-off-by: Dmitry Dunaev <dmitry@opsfleet.com>

[WIFI-10910] Chg: internal endpoint port

---

lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralUtils.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/channel/ChannelOptimizer.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/channel/LeastUsedChannelOptimizer.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/channel/RandomChannelInitializer.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/channel/LeastUsedChannelOptimizerTest.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/channel/UnmanagedApAwareChannelOptimizerTest.java

Move AVAILABLE_CHANNELS_BAND to UCentralUtils before adding 6G support. (Separating changes related to moving this constant from the more 6G-specific changes to come)

Move AVAILABLE_CHANNELS_BAND to UCentralUtils before adding 6G support

---

owrrm/src/main/java/com/facebook/openwifi/rrm/CustomJettyServerFactory.java

Fix javadoc and add override decorator

Fix javadoc and add override decorator

---

Dockerfile-hotspot
runner.sh

1. Enabled App CDS (Class Data Sharing) with the hopes that I'd see some performance improvement (no such luck - at least in memory).
2. Added ability to pass in extra JVM flags in runner.sh - this is useful

Add CDS for hotspot and ability to add extra JVM flags in runner

---

lib-rca/src/main/java/com/facebook/openwifi/librca/inputs/RCAParams.java
owrrm/src/main/java/com/facebook/openwifi/rrm/rca/modules/StationPinger.java

Add rca params

---

owrrm/openapi.yaml
owrrm/src/main/java/com/facebook/openwifi/rrm/RRMAlgorithm.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/clientsteering/ClientSteeringOptimizer.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/clientsteering/ClientSteeringState.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/clientsteering/SingleAPBandSteering.java
owrrm/src/main/java/com/facebook/openwifi/rrm/rca/modules/StationPinger.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/clientsteering/ClientSteeringOptimizerTest.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/clientsteering/ClientSteeringStateTest.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/clientsteering/SingleAPBandSteeringTest.java

Prepare for client steering: add simple logic to the cloud and make it callable (one-off or scheduled, still no trigger detection), but the actual steering of clients is not implemented yet.

Prepare for client steering

---

lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/AggregatedState.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/clientsteering/SingleAPBandSteering.java
owrrm/src/test/java/com/facebook/openwifi/rrm/modules/ModelerUtilsTest.java
owrrm/src/test/java/com/facebook/openwifi/rrm/modules/ProvMonitorTest.java

Fix errors introduced in recent commits.

Fix several compile errors/warnings

---

owrrm/src/main/java/com/facebook/openwifi/rrm/modules/ConfigManager.java

Remove persistent member `ConfigManager.DeviceData.config` as it is fetched every time anyway, which reduces overall memory requirements for the service. (This is replaced with local/temporary variables.)

Remove device config schema copy in ConfigManager

---

lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/ies/package-info.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/kafka/package-info.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/ap/Capabilities.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/ap/State.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/ap/UCentralSchema.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/ap/WifiScanEntryResult.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/ap/package-info.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/gw/package-info.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/prov/package-info.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/prov/rrm/package-info.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/package-info.java
lib-rca/src/main/java/com/facebook/openwifi/librca/package-info.java
owrrm/src/main/java/com/facebook/openwifi/rrm/modules/package-info.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/channel/package-info.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/clientsteering/package-info.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/package-info.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/tpc/package-info.java
owrrm/src/main/java/com/facebook/openwifi/rrm/package-info.java
owrrm/src/main/java/com/facebook/openwifi/rrm/rca/package-info.java
pom.xml

Add `package-info.java` and other missing Javadoc fields.

Add package-info.java and other class-level javadocs
