src/main/java/com/facebook/openwifirrm/modules/ProvMonitor.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralClient.java
src/main/java/com/facebook/openwifirrm/ucentral/prov/models/DeviceRules.java
src/main/java/com/facebook/openwifirrm/ucentral/prov/models/DiGraph.java
src/main/java/com/facebook/openwifirrm/ucentral/prov/models/DiGraphEntry.java
src/main/java/com/facebook/openwifirrm/ucentral/prov/models/Entity.java
src/main/java/com/facebook/openwifirrm/ucentral/prov/models/EntityList.java
src/main/java/com/facebook/openwifirrm/ucentral/prov/models/InventoryTag.java
src/main/java/com/facebook/openwifirrm/ucentral/prov/models/InventoryTagList.java
src/main/java/com/facebook/openwifirrm/ucentral/prov/models/SerialNumberList.java
src/test/java/com/facebook/openwifirrm/modules/ProvMonitorTest.java

Sync RRM topology and device configs with owprov venues and RRM configs. This is a first working version only and the design may change later. See examples below for an illustration of how this data is translated.
This PR contains a lot of models translated from owprov OpenAPI definition @ https://github.com/Telecominfraproject/wlan-cloud-owprov/blob/5945d02b3de3df100616bd8599914cd6faba000d/openapi/owprov.yaml.
```
2022-07-11T18:09:48.220 INFO  [ProvMonitor:146] - Synced topology with owprov: 4 zone(s), 5 total device(s)
2022-07-11T18:09:48.225 INFO  [ProvMonitor:170] - Synced device configs with owprov: RRM enabled on 2/5 device(s)
```
`topology.json`
```json
{
"%OWPROV_UNKNOWN_VENUE%": [
"00000000000c"
],
"sub-ven-A-1-i": [
"00000000000e"
],
"ven-A-1": [
"00000000000a",
"00000000000d" …
```

[WIFI-9979] Sync to owprov venues and RRM config

---

src/main/java/com/facebook/openwifirrm/RRMConfig.java
src/main/java/com/facebook/openwifirrm/modules/ConfigManager.java
src/main/java/com/facebook/openwifirrm/modules/DataCollector.java
src/main/java/com/facebook/openwifirrm/modules/Modeler.java
src/main/java/com/facebook/openwifirrm/modules/ProvMonitor.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralClient.java

- Pass correct "X-API-KEY" when using internal endpoints (messed up during rebase)
- Use default private endpoint which corresponds to HTTP port used (can be changed later, but should be consistent)
- Turn off HTTP basic auth by default
- Modules now do a *short* wait-loop while waiting for endpoints, as the regular application loops may be very long
- Consolidate some spammy debug logs

Fix internal auth, default RRM config, and module init loops

---

src/main/java/com/facebook/openwifirrm/RRM.java
src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralClient.java
src/main/java/com/facebook/openwifirrm/ucentral/gw/models/AclTemplate.java
src/main/java/com/facebook/openwifirrm/ucentral/gw/models/MfaAuthInfo.java
src/main/java/com/facebook/openwifirrm/ucentral/gw/models/MobilePhoneNumber.java
src/main/java/com/facebook/openwifirrm/ucentral/gw/models/TokenValidationResult.java
src/main/java/com/facebook/openwifirrm/ucentral/gw/models/UserInfo.java
src/main/java/com/facebook/openwifirrm/ucentral/gw/models/UserLoginLoginExtensions.java
src/main/java/com/facebook/openwifirrm/ucentral/gw/models/WebTokenAclTemplate.java
src/main/java/com/facebook/openwifirrm/ucentral/gw/models/WebTokenResult.java
src/test/java/com/facebook/openwifirrm/modules/ApiServerTest.java

Implement `validateToken` in `uCentralClient` and call from ApiServer to make sure that the request is valid. 
Generated a token, then tested
```
$ curl -k -H "Accept: application/json" -H "Authorization: Bearer SOME_GOOD_TOKEN" -i 'localhost:16789/api/v1/getTopology'
HTTP/1.1 200 OK
Date: Thu, 28 Jul 2022 21:42:08 GMT
Server:
Content-Type: application/json
Transfer-Encoding: chunked
$ curl -k -H "Accept: application/json" -H "Authorization: Bearer SOME_BAD_TOKEN" -i 'localhost:16789/api/v1/getTopology'
HTTP/1.1 403 Forbidden
Date: Thu, 28 Jul 2022 21:42:14 GMT
Server:
Content-Type: text/html;charset=utf-8
Transfer-Encoding: chunked
```

implement validateToken and wire it up in ApiServer

---

IMPLEMENTATION.md
pom.xml
src/main/java/com/facebook/openwifirrm/DeviceConfig.java
src/main/java/com/facebook/openwifirrm/DeviceDataManager.java
src/main/java/com/facebook/openwifirrm/RRM.java
src/main/java/com/facebook/openwifirrm/RRMConfig.java
src/main/java/com/facebook/openwifirrm/RRMSchedule.java
src/main/java/com/facebook/openwifirrm/Utils.java
src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
src/main/java/com/facebook/openwifirrm/modules/Modeler.java
src/main/java/com/facebook/openwifirrm/modules/ProvMonitor.java
src/main/java/com/facebook/openwifirrm/modules/RRMScheduler.java
src/test/java/com/facebook/openwifirrm/DeviceDataManagerTest.java
src/test/java/com/facebook/openwifirrm/modules/ApiServerTest.java
src/test/java/com/facebook/openwifirrm/modules/ProvMonitorTest.java

Allow scheduling RRM algorithms to be run per zone. This implementation uses the Quartz Job Scheduler library.
- Add "schedule" (`RRMSchedule`) field to `DeviceConfig`, which is only read at the network/zone layer (i.e. ignored at AP layer). This allows scheduling specified algorithms at a given interval in Quartz's cron-like format.
- Add `RRMScheduler` module encapsulating all Quartz implementation details and RRM execution.
- Add `RRMScheduler.syncTriggers()` calls throughout codebase as needed to ensure triggers remain in sync with topology and device config.
- Add "schedulerParams" (`RRMSchedulerParams`) structure to `RRMConfig`, which currently only allows specifying thread pool size.
**The config field names …

[WIFI-9980] Add RRM scheduler

---

README.md
openapi.yaml
pom.xml

Use "swagger-maven-plugin" to generate `openapi.yaml` during the "mvn compile" phase and check it into the repo. This file is not used for anything else.

[WIFI-9985] Generate openapi.yaml during mvn compile

---

openapi.yaml
src/main/java/com/facebook/openwifirrm/RRMConfig.java
src/main/java/com/facebook/openwifirrm/Utils.java
src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralClient.java

Clean up some of the OpenWiFi auth code.
- Only block RRM API paths ("/api/...") behind auth validators.
- Add bearer authentication scheme to OpenAPI document via annotations. This also enables the security forms in Swagger UI.
- Move uCentralSec token cache out of `UCentralClient` and into `ApiServer` as this will probably be the only user of it, and makes the HTTP client class cleaner.
- Add simple synchronized LRU cache implementation for uCentralSec token lookups. This only stores *successful* lookups and not *failed* lookups. Cache size can be configured via `APISERVERPARAMS_OPENWIFIAUTHCACHESIZE`.

[WIFI-9987] Improve OpenWiFi auth

---

src/main/java/com/facebook/openwifirrm/RRM.java
src/main/java/com/facebook/openwifirrm/RRMConfig.java
src/main/java/com/facebook/openwifirrm/modules/ProvMonitor.java
src/main/java/com/facebook/openwifirrm/modules/RRMScheduler.java
src/main/java/com/facebook/openwifirrm/optimizers/MeasurementBasedApApTPC.java
src/test/java/com/facebook/openwifirrm/modules/ProvMonitorTest.java

- Fix crash in `MeasurementBasedApApTPC.getCurrentTxPower()` if "tx-power" field is missing
- Add missing `Modeler.revalidate()` call to `ProvMonitor` after sync
- Add RRM config `SCHEDULERPARAMS_DRYRUN` (default false) for debugging the scheduler

Misc fixes

---

pom.xml
src/main/java/com/facebook/openwifirrm/Launcher.java
src/main/java/com/facebook/openwifirrm/RRM.java
src/main/java/com/facebook/openwifirrm/Utils.java
src/main/java/com/facebook/openwifirrm/VersionProvider.java
src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
src/main/resources-filtered/version.txt
src/test/java/com/facebook/openwifirrm/modules/ApiServerTest.java

Generate `version.txt` in classpath via Maven `project.version`, and read this in Java code instead of hardcoding it separately. This does not solve the `@OpenAPIDefinition` "version" problem though.
```bash
$ java -jar target/openwifi-rrm.jar -V
1.0.0
```

Generate version.txt via maven

---

src/main/java/com/facebook/openwifirrm/ucentral/UCentralApConfiguration.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralUtils.java

Handle edge/error cases better in `UCentralApConfiguration`. Specifically fixes NPE seen when device config contains no "radios".

Improve error handling in UCentralApConfiguration

---

ALGORITHMS.md
openapi.yaml
src/main/java/com/facebook/openwifirrm/RRM.java
src/main/java/com/facebook/openwifirrm/RRMAlgorithm.java
src/main/java/com/facebook/openwifirrm/RRMConfig.java
src/main/java/com/facebook/openwifirrm/RRMSchedule.java
src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
src/main/java/com/facebook/openwifirrm/modules/RRMScheduler.java
src/main/java/com/facebook/openwifirrm/optimizers/ChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/optimizers/LeastUsedChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/optimizers/LocationBasedOptimalTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/MeasurementBasedApApTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/MeasurementBasedApClientTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/RandomChannelInitializer.java
src/main/java/com/facebook/openwifirrm/optimizers/RandomTxPowerInitializer.java
src/main/java/com/facebook/openwifirrm/optimizers/UnmanagedApAwareChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/ucentral/prov/rrm/models/Algorithm.java
src/main/java/com/facebook/openwifirrm/ucentral/prov/rrm/models/Provider.java
src/test/java/com/facebook/openwifirrm/modules/ApiServerTest.java

Implement owprov `rrm_provider.yaml` API: https://github.com/Telecominfraproject/wlan-cloud-owprov/blob/efd7ef2a9b5958fc699c3adbbee9923959054338/openapi/rrm_provider.yaml
- `GET /api/v1/provider`
- `GET /api/v1/algorithms`
- `PUT /api/v1/runRRM`
Details:
- Create `RRMAlgorithm` class which consolidates some previously duplicated logic for executing RRM algorithms in `ApiServer` and `RRMScheduler`.
- `AlgorithmType` enum is now used for owprov APIs as well as scheduler config
- `AlgorithmResult` encapsulates possible responses and is returned by `PUT /api/v1/runRRM`
- Algorithm arguments from owprov APIs are parsed as comma-separated key=value pairs
- Add several `ServiceConfig` fields to handle new owprov API getters.
- Move "mode" names into optimizer classes as a static field …

[WIFI-10341] Implement owprov RRM API

---

openapi.yaml
src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
src/main/resources/public/swagger-initializer.js

- Add missing 400 response codes in several endpoint descriptions
- Disable syntax highlighting in Swagger UI because it causes large (~1mb+) response bodies to hang the UI

OpenAPI fixes

---

.github/workflows/deploy-gh-pages.yml
README.md
pom.xml
src/main/java/com/facebook/openwifirrm/DeviceDataManager.java
src/main/java/com/facebook/openwifirrm/Launcher.java
src/main/java/com/facebook/openwifirrm/RRMAlgorithm.java
src/main/java/com/facebook/openwifirrm/RRMConfig.java
src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
src/main/java/com/facebook/openwifirrm/optimizers/TPC.java
src/main/javadoc/overview.html

- Add Javadoc config section to `pom.xml`
- Fix Javadoc errors in sources
- Add minimal `overview.html` to be placed on generated index page
- Add GitHub workflow to build Javadoc on push and deploy to gh-pages branch

Configure javadoc, fix errors, deploy to gh-pages

---

src/main/java/com/facebook/openwifirrm/RRMConfig.java
src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
src/test/java/com/facebook/openwifirrm/modules/ApiServerTest.java

Add proper CORS support to `ApiServer`.
- Add global HTTP `OPTIONS` handler to reflect requested options.
- Add "Access-Control-Allow-Origin" response header (and "Vary") whenever "Origin" request header is present, *if* CORS checks pass based on `APISERVERPARAMS_CORSDOMAINLIST` RRM config:
- If set, origin must match a domain in this comma-separated list.
- If empty, always reflect the "Origin" header (i.e. allow all origins).

[WIFI-9985] Add CORS support

---

src/main/java/com/facebook/openwifirrm/DeviceDataManager.java
src/main/java/com/facebook/openwifirrm/Launcher.java

Handle blank input files (blank meaning containing no characters or only whitespace), which was not handled before. Only "empty JSONs" (i.e., `{}`) were handled before.
Signed-off-by: Rocky Mandayam <rockymandayam@fb.com>

Handle empty topology file

---

Dockerfile
openapi.yaml
pom.xml
scripts/get_build_version.sh
src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
src/main/resources-filtered/version.txt

Update package version from 1.0.0 to 2.7.0, both in `pom.xml` and `ApiServer.java`.
Define a new `appendVersionString` property in Maven which gets added to the generated (filtered) `version.txt` resource (used to source the version string at runtime). In the `Dockerfile`, set this property to a combination of Git hash and build number when available (via new script `scripts/get_build_version.sh`).
Example output:
```
$ docker build -f Dockerfile .
Successfully built 0c3cabe843d1
$ docker run --rm -it 0c3cabe843d1 /bin/bash
2.7.0-ebed9b5(32)
```

Update package version to 2.7.0, append git info during docker builds

---

src/main/java/com/facebook/openwifirrm/Launcher.java
src/main/java/com/facebook/openwifirrm/RRMConfig.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralClient.java

Instead of hardcoded disabling of SSL validation (i.e. `Unirest.config().verifySsl(false)`), move this into `RRMConfig` as `UCENTRALCONFIG_VERIFYSSL`, still default off.

Move SSL validation toggle into RRMConfig

---

.github/workflows/ci.yml
scripts/get_build_version.sh

Build version was not being correctly generated in workflows due to shallow clone. Change this to a full clone with history using the new fetch depth parameter from https://github.com/Telecominfraproject/.github/pull/7 (`checkout_fetch_depth`).

Fix build version generation in CI/CD

---

src/main/java/com/facebook/openwifirrm/Launcher.java
src/main/java/com/facebook/openwifirrm/RRMConfig.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralKafkaConsumer.java

Move hardcoded Kafka consumer poll timeout (used when fetching topics and records) into `RRMConfig` as `KAFKACONFIG_POLLTIMEOUTMS`, keeping the same default of 10 seconds.

Move Kafka consumer poll timeout to RRMConfig

---

src/main/java/com/facebook/openwifirrm/modules/DataCollector.java

In `DataCollector`, check if a device is online/connected before trying to send a wifi scan or capabilities request. (This is already checked in `ConfigManager`.)

Add missing device connection status checks in DataCollector

---

src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPC.java
src/main/java/com/facebook/openwifirrm/ucentral/models/WifiScanEntryResult.java

Fix javadoc warnings (`mvn javadoc:javadoc` succeeds now)

Fix javadoc warnings

---

src/main/java/com/facebook/openwifirrm/optimizers/tpc/RandomTxPowerInitializer.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPCTest.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/RandomTxPowerInitializerTest.java

1. Enable Random tx Power Initializer in 2G.
2. Add unit test to cover all bands and default tx power.

Enable Random Tx Power Initializer in 2G

---

README.md
pom.xml
spotless/eclipse-java-formatter.xml
spotless/license-header.txt
src/main/java/com/facebook/openwifirrm/DeviceDataManager.java
src/main/java/com/facebook/openwifirrm/RRMConfig.java
src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
src/main/java/com/facebook/openwifirrm/modules/ProvMonitor.java
src/main/java/com/facebook/openwifirrm/mysql/DatabaseManager.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/ChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/LocationBasedOptimalTPC.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralClient.java
src/test/java/com/facebook/openwifirrm/modules/DataCollectorTest.java
src/test/java/com/facebook/openwifirrm/optimizers/TestUtils.java

Add Java code auto-formatter config using Spotless (Maven) with the Eclipse JDT formatter. Add a custom Eclipse style XML which closely matches the existing (manual) code style.
To run the auto-formatter, use `mvn spotless:apply`. **This PR does not apply code changes. They will be applied later.**
Notable style differences (mainly due to formatter limitations):
- 80 chars per line will be enforced (except in some odd cases)
- Spacing around binary operators will be enforced (mostly)
- Even if 2+ arguments fit on a single overflow line, they will still be split 1-per-line
- Array initializers will be split 1-per-line
- 1 space preceding inline comment (previously 2 spaces)
- Overflow indentation will be applied in condition expressions
Notable formatter settings:
- Comment formatting is …

Add autoformatter (Spotless with Maven, Eclipse JDT)

---

src/main/java/com/facebook/openwifirrm/RRM.java
src/main/java/com/facebook/openwifirrm/Utils.java
src/main/java/com/facebook/openwifirrm/modules/DataCollector.java

Set thread names for all program threads (modules and executors). `NamedThreadFactory` is a copy of `Executors.DefaultThreadFactory` which accepts a name prefix.

Set thread names

---

Dockerfile

"docker-library/openjdk" is deprecated, so switch to another JDK image (AdoptOpenJDK). While here, switch from HotSpot to Eclipse OpenJ9 JVM, and tweak some JVM flags, in an attempt to reduce resource usage.
- Idle memory (RSS): ~200MB before (HotSpot), ~120MB after (OpenJ9)
- CPU: not measured at this time
Tested by restarting containers and fetching OpenAPI document to memory (by loading `/` in a browser).

Update Dockerfile to use OpenJ9 JVM

---

openapi.yaml
src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
src/test/java/com/facebook/openwifirrm/modules/ApiServerTest.java

This PR implemented a POST command required by OpenWifi SDK. 
- In `ApiServer.java`, add a new EndPoint `SetSystemEndpoint` to implement POST.
-- requestBody: Parse this as a JSONObject as  the value of Schema.implementation 
--  responses: Content of `Schema` is Object.class and leave a TODO comment in the code. Simply return "[]" for each valid command.
- Add unit test in `ApiServerTest.java` to test the changes.
- openapi.yaml is auto-generated
Test plan:
1. valid command: `{"command": "getloglevelnames"}`
2. invalid command: `{"command": "xx"}`
3. invalid command: : `{"xx": "xx"}`

Implement a POST/system command required by OpenWIFI SDK

---

src/main/java/com/facebook/openwifirrm/modules/ProvMonitor.java

Provisioning service had a bug where it allowed duplicate devices across different venues. RRM has the functionality to check for it but upon receiving this bad data, it will just crash the whole process. Handle it gracefully by handling `IllegalArgumentException`, log the error, and just abort the sync.
Open question:
- How do I test? I thought I'd go about mocking it but looking at the testing framework used (Junit), mocking is not included. Should I bring in Mockito, mock out the client and test?

[WIFI-10655] Gracefully abort topology sync with prov in case of bad data

---

src/main/java/com/facebook/openwifirrm/optimizers/channel/RandomChannelInitializer.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/RandomTxPowerInitializer.java
src/test/java/com/facebook/openwifirrm/optimizers/channel/RandomChannelInitializerTest.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/RandomTxPowerInitializerTest.java

Previously both `RandomChannelInitializer` and `RandomTxPowerInitializer` would initialize a single random value to use across APs. Introduce another constructor to allow setting a different random value PER AP.
In addition:
- Make  `RandomTxPowerInitializer` follow `RandomChannelInitializer`'s lead in terms of how random values are generated. Instead of holding an attribute for the generated value, it'll be generated on the fly since the value isn't used outside of computing the map.
- Add another constructor that also allows passing in a `Random` instance to allow seeding, making testing possible by having the number generation deterministic. I didn't expose a method for setting the seed as that would introduce weird cases where numbers could have been generated but then the seed was …

[WIFI-10593] Allow different values per AP for `RandomChannelInitializer` and `RandomTxPowerInitializer`

---

src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPC.java
src/test/java/com/facebook/openwifirrm/optimizers/TestUtils.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPCTest.java

In `MeasurementBasedApApTPC`, make sure it only sets tx power  for a (device, band) if that device operates in that band. This PR includes:
- A few lines in `MeasurementBasedApApTPC` to implement this behavior
- Many changes in `MeasurementBasedApApTPCTest` to test the behavior
- Changes to `TestUtils` both to support the changes in `MeasurementBasedApApTPCTest` and to fix a minor bug from a previous PR

Add multi-band check for MeasurementBasedApApTPC

---

src/main/java/com/facebook/openwifirrm/optimizers/channel/RandomChannelInitializer.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/RandomTxPowerInitializer.java

I didn't apply this in #47 so fix it in this PR
- reorder constructor
- change `RandomTxPowerInitializer` to cascade constructors properly

reorder constructor for `RandomChannelInitializer` and `RandomTxPowerInitializer`

---

src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApClientTPC.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralUtils.java
src/test/java/com/facebook/openwifirrm/optimizers/TestUtils.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApClientTPCTest.java

1. Add a new util method to determine the band with the given channel.
2. Instead of only using the first radio, iterate over all the radios for each device when compute Tx power in `MeasurementBasedApClientTPC`.
3. Instead of hardcode the band as `5G`, leverage the new method to determine the band for each radio.
4. Add test cases for the changes.
@pohanhf some questions regarding the radios and channels:
1. Is it possible to have a channel that cannot be mapped to either 2G or 5G?
2. Is it possible to have a device with two channels mapping to the same band? e.g. A device with two radios, whose channels are 36 and 60.

Enable MeasurementBasedApClientTPC in 2G

---

ALGORITHMS.md
src/main/java/com/facebook/openwifirrm/RRMAlgorithm.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/LeastUsedChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/RandomChannelInitializer.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/UnmanagedApAwareChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/LocationBasedOptimalTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApClientTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/RandomTxPowerInitializer.java

Args were being parsed out but not actually passed into the constructors. Create and call a factory method to call the proper constructors based on what's present in the generic args map for all the algorithms available. Also updated ALGORITHMS.md with the available args for each algorithm.

Pass down RRM algorithm parameters

---

src/main/java/com/facebook/openwifirrm/DeviceConfig.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/LocationBasedOptimalTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApClientTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/RandomTxPowerInitializer.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/TPC.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/LocationBasedOptimalTPCTest.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPCTest.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApClientTPCTest.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/RandomTxPowerInitializerTest.java

The TPC algorithms did not use some user config fields from DeviceConfig (the device configuration):
- allowedTxPowers
- userTxPowers
This PR uses those field in TPC algorithms.
Here's the list of major updates and some questions:
1. For available channel lists, we have different default channel lists for different channel widths and bands, but for TPC we don't. I use all the tx powers in the range of [`MIN_TX_POWER`, `MAX_TX_POWER`] as default for now. Any idea to have more specific default? @pohanhf 
2. `RandomTxPowerIntializer`: since different AP and band may have different available tx powers now, `setDifferentTxPowerPerAp` is removed. If we want to keep this arg, we can pick random one from the common tx power choices.
3. `LocationBasedOptimalTPC`: leverage the new method when …

Use TPC user configs (allowedTxPowers, userTxPowers)

---

src/main/java/com/facebook/openwifirrm/optimizers/tpc/LocationBasedOptimalTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/RandomTxPowerInitializer.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/TPC.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/LocationBasedOptimalTPCTest.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPCTest.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/RandomTxPowerInitializerTest.java

Signed-off-by: Wuwei Cai <wuweicai@fb.com>
Implement per-channel operation to all TPC optimizers. This PR also fixes the bug that TPC always run for both 2G and 5G bands for `LocationBasedOptimalTPC`, `MeasurementApApTPC` and `RandomTxPowerInitializer`.
1. New method `getApsPerChannel` in the base `TPC` class. 
2. For `LocationBasedOptimalTPC`, instead of running algorithm per band, only consider APs with the same channel.
3. For `MeasurementApApTPC` and `RandomTxPowerInitializer`, only runs TPC on bands with channels on each AP.
1. Per-band TPC test ran as expected with real APs
2. Modified the unit tests and tested with the cases that not channels in both 2G and 5G bands are used for each device.

Implement per-channel TPC

---

scripts/k6/simple.js

Add a directory for [k6](https://github.com/grafana/k6) scripts. K6 is a loadtesting tool which gets configured by javascript and is very flexible AFAIK. I thought it'd be worth to have a base set of scripts for getting performance results. This adds a simple test that just calls a bunch of GET requests.
Maybe in the future we can also add a check for PRs or something - but for now occasional ad-hoc runs are still useful.
```
$ k6 run scripts/k6/simple.js --duration 10s
/\      |‾‾| /‾‾/   /‾‾/
/\  /  \     |  |/  /   /  /
/  \/    \    |     (   /   ‾‾\
/          \   |  |\  \ |  (‾)  |
/ __________ \  |__| \__\ \_____/ .io
execution: local
script: scripts/k6/simple.js
output: -
scenarios: (100.00%) 1 scenario, 1 max VUs, 40s max duration (incl. graceful stop):
* default: 1 looping VUs …
```

Add a simple k6 script for loadtesting/benching

---

src/main/java/com/facebook/openwifirrm/modules/Modeler.java
src/main/java/com/facebook/openwifirrm/mysql/DatabaseManager.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/ChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/LeastUsedChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/RandomChannelInitializer.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApClientTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/TPC.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralUtils.java
src/main/java/com/facebook/openwifirrm/ucentral/models/State.java
src/test/java/com/facebook/openwifirrm/optimizers/TestUtils.java
src/test/java/com/facebook/openwifirrm/optimizers/channel/LeastUsedChannelOptimizerTest.java
src/test/java/com/facebook/openwifirrm/optimizers/channel/RandomChannelInitializerTest.java
src/test/java/com/facebook/openwifirrm/optimizers/channel/UnmanagedApAwareChannelOptimizerTest.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/LocationBasedOptimalTPCTest.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPCTest.java

It was possible that the configuration would not have the tx power, which would cause the algorithm to not run. However, with this change tx power will be sourced from statistics instead which should always have tx power. 
- Typed `State`'s `Radio` object. This required changes across a number of files.
- channel width is string, why???
- Changed `latestDeviceStatus` to `latestDeviceStatusRadios`. This is much clearer since the previous name was confused with `latestState`
Previously, we just took the first SSID of the first interface to run TPC on. This is wrong as the first SSID won't necessarily match up with the band requested (i.e. working on 2.4 but 5 could be retrieved and vice versa). Loop through the interfaces as well as SSID in order to find the correct SSID for the band.

Make AP-AP TPC algorithm use tx power from statistics and fix TPC application to correct band

---

src/test/java/com/facebook/openwifirrm/optimizers/TestUtils.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPCTest.java

- Replace `createModel` into `createModelSingleBand` and `createModelDualBand`. Some of the tests earlier were using `createModel` (which did dual band) when they really only should have been single band (though this didn't affect the test).
- "synced" state and status (e.g., if an AP has a 5G radio in state, it should have it in status, and vice versa)
- instead of using "device B" to test what happens when an AP does not have a 5G radio, use device C. This is done to make it consistent with the existing wifiscans which show device B in the 5G band

Measurement based ap ap tpc test fix

---

src/main/java/com/facebook/openwifirrm/ucentral/operationelement/VHTOperationElement.java
src/test/java/com/facebook/openwifirrm/ucentral/operationelement/VHTOperationElementTest.java

Use `short` instead of `byte` to store unsigned byte values in VHTOperationElement. Confirmed by reading channel 155 from a vht IE from a real AP.
Will be cherry-picked into 2.7 release after this is merged into main.

Use short instead of byte to store unsigned byte values in VHTOperationElement

---

src/main/java/com/facebook/openwifirrm/modules/ApiServer.java

`validateToken` already tries to validate normal tokens and subscriber tokens so there is no need to call `validateSubToken` separately: https://github.com/Telecominfraproject/wlan-cloud-ucentralsec/blob/adce4a823856c60a4a88980cfaa4e76ece432e2d/src/AuthService.cpp#L726-L745

Update comments about validating tokens

---

src/main/java/com/facebook/openwifirrm/modules/ApiServer.java

Clarified with Stephane that the validation of subtokens within the `validateToken` is a bug. This has been addressed so update the comment on RRM's end: https://github.com/Telecominfraproject/wlan-cloud-ucentralsec/pull/75

Update comment around token validation to clarify behavior

---

src/main/java/com/facebook/openwifirrm/ucentral/operationelement/VHTOperationElement.java
src/test/java/com/facebook/openwifirrm/ucentral/operationelement/VHTOperationElementTest.java

Cherry-pick #81 into release/v2.7.0 to address allow `VHTOperationElement` to store channel numbers greater than 127.
https://telecominfraproject.atlassian.net/browse/WIFI-10911

[WIFI-10911] Use short instead of byte to store unsigned byte values in VHTOperationElement

---

src/main/java/com/facebook/openwifirrm/modules/ModelerUtils.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/ChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralUtils.java
src/main/java/com/facebook/openwifirrm/ucentral/WifiScanEntry.java
src/main/java/com/facebook/openwifirrm/ucentral/informationelement/Country.java
src/main/java/com/facebook/openwifirrm/ucentral/informationelement/HTOperationElement.java
src/main/java/com/facebook/openwifirrm/ucentral/informationelement/LocalPowerConstraint.java
src/main/java/com/facebook/openwifirrm/ucentral/informationelement/QbssLoad.java
src/main/java/com/facebook/openwifirrm/ucentral/informationelement/TxPwrInfo.java
src/main/java/com/facebook/openwifirrm/ucentral/informationelement/VHTOperationElement.java
src/main/java/com/facebook/openwifirrm/ucentral/models/WifiScanEntryResult.java
src/test/java/com/facebook/openwifirrm/ucentral/informationelement/HTOperationElementTest.java
src/test/java/com/facebook/openwifirrm/ucentral/informationelement/VHTOperationElementTest.java

Discard unneeded ies and keep the relevant ones:
- Remove the ies field
- Parse out specific ies and put them in their own fields
There are other relevant IEs, but they won't be used just yet and their accuracy needs to be confirmed, so they will come in a separate PR.

Discard unneeded ies

---

openapi.yaml
src/main/java/com/facebook/openwifirrm/RRMSchedule.java
src/main/java/com/facebook/openwifirrm/modules/ProvMonitor.java
src/main/java/com/facebook/openwifirrm/modules/RRMScheduler.java
src/test/java/com/facebook/openwifirrm/modules/RRMSchedulerTest.java

Linux cron is weird and ORs the day of month and day of week values are both not `*`. Quartz is even weirder in that it can't support crons with both values specified.
>  Note: The day of a command's execution can be specified in the
following two fields — 'day of month', and 'day of week'.  If
both fields are restricted (i.e., do not contain the "*"
character), the command will be run when either field matches the
current time.  For example,
"30 4 1,15 * 5" would cause a command to be run at 4:30 am on the
1st and 15th of each month, plus every Friday.
From https://man7.org/linux/man-pages/man5/crontab.5.html
Since it's simply matching either of them, split them out into two different crons and register them both. I had to change the type of a field, which may or may not cause problems …

[WIFI-10819] parse cron into valid quartz cron

---

src/main/java/com/facebook/openwifirrm/modules/ModelerUtils.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/ChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/ucentral/informationelement/HTOperation.java
src/main/java/com/facebook/openwifirrm/ucentral/informationelement/VHTOperation.java
src/test/java/com/facebook/openwifirrm/ucentral/informationelement/HTOperationTest.java
src/test/java/com/facebook/openwifirrm/ucentral/informationelement/VHTOperationTest.java

Rename HTOperationElement, HTOperationElementTest, VHTOperationElement, and VHTOperationElementTest for consistency (all other classes in the package do not include the "Element" suffix)

Rename HTOperationElement, HTOperationElementTest, VHTOperationElement, and VHTOperationElementTest

---

src/main/java/com/facebook/openwifirrm/optimizers/channel/ChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralUtils.java
src/test/java/com/facebook/openwifirrm/ucentral/UCentralUtilsTest.java

1. "auto" is a valid value in configuration - there was an assumption that it was only an int and it tried to call `getAsInt()` without any safeguards. This caused the exception to propagate up (not caught anywhere) and crash the system.
1. https://github.com/Telecominfraproject/wlan-ucentral-schema/blob/bfcb0e8c6e6c07195ba964f696c562aae3723fa3/schema/radio.yml#L27-L36
3. 80p80 was represented as 8080, which is problematic as the value is taken at face value i.e. it's used directly in computations. So it was seen has 8080MHz instead of the proper 80p80 it is. @pohanhf can speak more to this.

[WIFI-10943] Deal with "auto" value for channel and fix 80p80 representation

---

src/main/java/com/facebook/openwifirrm/optimizers/channel/ChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/ucentral/UCentralUtils.java
src/test/java/com/facebook/openwifirrm/ucentral/UCentralUtilsTest.java

[WIFI-10943] Deal with "auto" value for channel and fix 80p80 representation, so RRM service does not keep restarting.
[WIFI-10943]: https://telecominfraproject.atlassian.net/browse/WIFI-10943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WIFI-10943] Deal with "auto" value for channel and fix 80p80 representation (#92)

---

src/main/java/com/facebook/openwifirrm/ucentral/UCentralUtils.java

Handle IEs (before the try-catch):
- without a TYPE field
- that aren't (json) objects
- without a contents field
Also, instead of printing the exception in the log debug message, print the IE that was skipped.

Handle invalid IEs

---

src/main/java/com/facebook/openwifirrm/RRMConfig.java
src/main/java/com/facebook/openwifirrm/modules/Modeler.java
src/main/java/com/facebook/openwifirrm/modules/ModelerUtils.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/ChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/LeastUsedChannelOptimizer.java
src/main/java/com/facebook/openwifirrm/optimizers/channel/RandomChannelInitializer.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/LocationBasedOptimalTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApClientTPC.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/RandomTxPowerInitializer.java
src/main/java/com/facebook/openwifirrm/optimizers/tpc/TPC.java
src/main/java/com/facebook/openwifirrm/ucentral/models/AggregatedState.java
src/test/java/com/facebook/openwifirrm/modules/ModelerUtilsTest.java
src/test/java/com/facebook/openwifirrm/optimizers/TestUtils.java
src/test/java/com/facebook/openwifirrm/optimizers/channel/LeastUsedChannelOptimizerTest.java
src/test/java/com/facebook/openwifirrm/optimizers/channel/RandomChannelInitializerTest.java
src/test/java/com/facebook/openwifirrm/optimizers/channel/UnmanagedApAwareChannelOptimizerTest.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/LocationBasedOptimalTPCTest.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPCTest.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApClientTPCTest.java
src/test/java/com/facebook/openwifirrm/optimizers/tpc/RandomTxPowerInitializerTest.java

Signed-off-by: zhiqiand <zhiqian@fb.com>
This PR aggregates State by bssid&station String and Radio. If two State matches in bssid, station, channel, channel_width and tx_power. Then the two need to be aggregated to an `AggregatedState`. In `AggregatedState`, rssi and mcs list all the values over the time.
The return aggregated map is a map from serial number to a map from bssid&station String to a list of `AggregatedState`.
`Map(Serial Number -> Map(bssid&station string -> List<AggregatedState>))`
Also keep only `latestStates` under `DataModel` instead of `latesState`. This PR fixes some bugs causing by this change.
For easy review, focus on `AggregatedState.java`, `ModelerUtils.java`, `ModelerUtilsTest.java` and `UtilsTest.java`.
- Create `AggregatedState` class, `AggregatedRate` and …

States aggregation 

---

src/main/java/com/facebook/openwifirrm/ucentral/UCentralUtils.java
src/main/java/com/facebook/openwifirrm/ucentral/informationelement/Country.java
src/main/java/com/facebook/openwifirrm/ucentral/informationelement/TxPwrInfo.java

Parsing for Country and Tx Power Info was wrong - they didn't take the actual inner element and tried to use the content value.
Tx Power Info also had type errors (Integer and int didn't line up between parsing and constructor) as well as wrong field names.

Fix IE parsing

---

src/main/java/com/facebook/openwifirrm/modules/Modeler.java
src/main/java/com/facebook/openwifirrm/ucentral/models/AggregatedState.java

Signed-off-by: zhiqiand <zhiqian@fb.com>
This PR should resolve some conversation from Jerrey in https://github.com/Telecominfraproject/wlan-cloud-rrm/pull/82
- Didn't use `sychronizedList` as it is thread-safe already. 
> In RRM algorithms, the whole DataModel is copied.
- Didn't override `hashCode()` in `AggregatedState`, use a check method instead. Remove `hashCode()` and `equals()`
-  use `while` loop to truncate the State buffer to the correct size.

Follow-up on stats aggregation

---

Dockerfile
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralClient.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/gw/WebTokenResult.java
owrrm/openapi.yaml
owrrm/src/main/java/com/facebook/openwifi/rrm/CustomJettyServerFactory.java
owrrm/src/main/java/com/facebook/openwifi/rrm/RRMConfig.java
owrrm/src/main/java/com/facebook/openwifi/rrm/modules/ApiServer.java
owrrm/src/test/java/com/facebook/openwifi/rrm/modules/ApiServerTest.java
owrrm/src/test/java/com/facebook/openwifi/rrm/services/MockOWSecService.java
scripts/k6/simple.js

Override the default embedded server, allowing us to define our own connectors. So define new parameters and pass them in to open another port for external calls. We already have the port information, so use that to determine whether it was an internal or external call in the request filter.
External, no `Authorization` header
```
$ http GET localhost:16790/api/v1/getTopology
HTTP/1.1 401 Unauthorized
Content-Type: text/html;charset=utf-8
Date: Wed, 14 Sep 2022 01:07:38 GMT
Server:
Transfer-Encoding: chunked
WWW-Authenticate: Bearer error="invalid_token"
```
External, bad token
```
% http GET localhost:16790/api/v1/getTopology 'Authorization: Bearer asd'
HTTP/1.1 401 Unauthorized
Content-Type: text/html;charset=utf-8
Date: Wed, 14 Sep 2022 01:08:56 GMT
Server:
Transfer-Encoding: chunked …
```

[WIFI-10736] Spin up separate ports for internal and external

---

lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralUtils.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/channel/LeastUsedChannelOptimizer.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/TestUtils.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/tpc/LocationBasedOptimalTPCTest.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/tpc/MeasurementBasedApApTPCTest.java

Remove lower and upper channel limit maps. This PR is just consolidating some logic/refactoring in separate PRs so the PR for supporting 6G isn't as large.
The lower and upper channel limit maps were removed since the information stored in them was already present in CHANNEL_AVAILABLE_BAND. It is easier to maintain fewer "sources of truth".

Remove lower and upper channel limit maps

---

lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralConstants.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralUtils.java
owrrm/src/main/java/com/facebook/openwifi/rrm/modules/ModelerUtils.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/channel/ChannelOptimizer.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/channel/LeastUsedChannelOptimizer.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/channel/RandomChannelInitializer.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/tpc/LocationBasedOptimalTPC.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/tpc/MeasurementBasedApApTPC.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/tpc/MeasurementBasedApClientTPC.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/tpc/RandomTxPowerInitializer.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/tpc/TPC.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/TestUtils.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/channel/LeastUsedChannelOptimizerTest.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/channel/RandomChannelInitializerTest.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/channel/UnmanagedApAwareChannelOptimizerTest.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/tpc/LocationBasedOptimalTPCTest.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/tpc/MeasurementBasedApApTPCTest.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/tpc/MeasurementBasedApClientTPCTest.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/tpc/RandomTxPowerInitializerTest.java

This is done in anticipation of adding 6G support. 6G uses the same channel numbers as other bands. E.g., channel 1 could refer to 2G channel 1 or 6G channel 1. Therefore, we cannot just infer band form channel anymore.
This PR makes sure we use device capabilities to identify a radio's band separately from its channel number, and that when we categorize radios based on channel, we also take band into account (i.e., we should categorize on the (band, channel) tuple instead).

Use device capabilities to identify radio band

---

owrrm/src/main/java/com/facebook/openwifi/rrm/CustomJettyServerFactory.java

I put the host as localhost which was stopping any outside service being able to talk to it properly in a normal deployment. 
```
$ netstat -anp tcp | rg '16789|16790'
tcp4       0      0  127.0.0.1.16789        *.*                    LISTEN
tcp4       0      0  127.0.0.1.16790        *.*                    LISTEN
$ netstat -anp tcp | rg '16789|16790'
tcp46      0      0  *.16789                *.*                    LISTEN
tcp46      0      0  *.16790                *.*                    LISTEN
```

[WIFI-11247] change host to 0.0.0.0

---

Dockerfile

`maven:3-jdk-11` uses `openjdk:11-jdk` which is an adoptjdk distro which is deprecated and not being updated anymore: https://adoptopenjdk.net/upstream.html
tested on m1 mbp:
```
$ docker buildx build --platform=linux/amd64 .
```

Use eclipse temurin distribution of openjdk for docker maven builds

---

lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralClient.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralUtils.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/ap/State.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/gw/ScriptRequest.java

Add the following new methods:
- `UCentralClient.runScript()` - run script on AP via ucentralgw (with new model `ScriptRequest`)
- `UCentralClient.pingFromDevice()` - run ping from AP (example/stub function using `runScript()`)
- `UCentralUtils.getScriptOutput()` - postprocess result of `UCentralClient.runScript()`
- `UCentralUtils.getWifiClientInfo()` - return STA MAC -> IP mapping from a State object
----
Test code using these new methods to ping all clients of OWF APs (in owrrm `ApiServer`):
```java
modeler.getDataModel().latestStates.forEach((serialNumber, states) -> {
State state = states.get(states.size() - 1);
Map<String, State.Interface.Client> clientMap = UCentralUtils.getWifiClientInfo(state);
if (clientMap.isEmpty()) {
return;
}
logger.info(
"**** Pinging clients for {} (total …
```

Add script API and some related utilities

---

Dockerfile
runner.sh

- adoptopenjdk is being dissolved, so users should move to eclipse temurin or ibm semeru. Since the former is hotspot based and we want openj9, use ibm semeru JUST FOR RUNTIME. We will still use eclipse temurin for building (although i think we can technically use semeru for building as well - don't have as much context here)
- a benefit of this is that there's aarch64 build so we can build/run native docker images on the ARM macbooks
- Add `runner.sh` to mirror running both in docker and locally. This will help speed up performance tuning

Move running image to ibm-semeru and introduce runner script

---

Dockerfile
runner.sh

Modify runner script to support different java binaries.
- Compact strings for both (default on openj9, but make it explicit)
- string deduplication for hotspot (seems to reduce a tiny amount of memory and g1 was already default gc so just make it explicity)

JVM options for strings

---

lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralClient.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralUtils.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/kafka/UCentralKafkaConsumer.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/ap/State.java
owrrm/src/main/java/com/facebook/openwifi/rrm/RRM.java
owrrm/src/main/java/com/facebook/openwifi/rrm/RRMConfig.java
owrrm/src/main/java/com/facebook/openwifi/rrm/modules/Modeler.java
owrrm/src/main/java/com/facebook/openwifi/rrm/rca/RCAConfig.java
owrrm/src/main/java/com/facebook/openwifi/rrm/rca/RCAUtils.java
owrrm/src/main/java/com/facebook/openwifi/rrm/rca/modules/StationPinger.java

Add RCA package (`com.facebook.openwifi.rrm.rca`) into RRM service. This package is designed to be very loosely integrated, and easily separated from RRM later if needed.
New classes:
- `RCAConfig` - service config, currently integrated into `RRMConfig.rcaConfig`
- `RCAUtils` - ping utilities (more later)
- `StationPinger` - station pinger service, currently instantiated by `RRM` **(disabled by default config)**
set `pingIntervalSec = 160`
```
2022-10-31T21:55:49.916 DEBUG [StationPinger:251] - <AP1>: Pinging client <STA1> (192.168.1.96)
2022-10-31T21:55:55.204 INFO  [StationPinger:269] - Ping result from <AP1> to <STA1> (192.168.1.96): 28.694/69.816/107.332/0.000 ms
...
2022-10-31T21:59:50.026 DEBUG …
```

Add station pinger to RRM service

---

.gitignore
Dockerfile-hotspot
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/AggregatedState.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/StateInfo.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralUtils.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/ap/State.java
owrrm/.gitignore
owrrm/src/main/java/com/facebook/openwifi/rrm/modules/Modeler.java
owrrm/src/main/java/com/facebook/openwifi/rrm/modules/ModelerUtils.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/channel/LeastUsedChannelOptimizer.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/channel/RandomChannelInitializer.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/tpc/LocationBasedOptimalTPC.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/tpc/MeasurementBasedApApTPC.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/tpc/MeasurementBasedApClientTPC.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/tpc/TPC.java
owrrm/src/test/java/com/facebook/openwifi/rrm/modules/ModelerUtilsTest.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/TestUtils.java
runner.sh

Signed-off-by: zhiqiand <zhiqian@fb.com>
This PR refactor `AggregatedState` to meet the input data standard of RCA. The input data structure of RCA will be defined later in a separate PR.
Quick review:
```
public class AggregatedState {   
public static class RadioConfig {
public int channel;
public int channelWidth;
public int txPower;
public String phy;
}
public class AssociationInfo {
public long activeMsRadio;
public long busyMsRadio;
public long noiseRadio;
public long receiveMsRadio;
public long transmitMsRadio;
public long connected;
public long inactive;
public int rssi;
public long rxBytes;
public long rxPackets;
public Rate rxRate;
public long txBytes;
public long txDuration;
public long txFailed;
public long txPackets;
public Rate txRate;
public long txRetries;
public int …
```

Refactor AggregatedState and add timestamp

---

lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/IEUtils.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/InformationElements.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralUtils.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/ies/RMEnabledCapabilities.java
owrrm/ALGORITHMS.md
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/clientsteering/ClientSteeringOptimizer.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/clientsteering/ClientSteeringState.java
owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/clientsteering/SingleAPBandSteering.java

Fill in a bit more of the initial client steering implementation, but still not enough to be functional.
- Add detailed TODO comments on commands which need to be sent to APs/clients
- Update docs at `ALGORITHMS.md`
- Parse `RMEnabledCapabilities` IE needed to determine 802.11k support
- Fix `backoffTimeNs` argument and change to `backoffTimeSec` (switch to more reasonable time unit)

Client steering notes, docs, fixes

---

lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralApConfiguration.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralUtils.java
lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/ap/UCentralSchema.java
owrrm/src/main/java/com/facebook/openwifi/rrm/modules/Modeler.java
owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/TestUtils.java

Convert `Modeler.DataModel.latestDeviceStatusRadios` value type from `JsonArray` to `UCentralSchema.Radio`, which brings some memory savings.
Supersedes #110, but omits the full switch of the `UCentralApConfiguration` underlying structure (still uses `JsonObject` instead of the new `UCentralSchema`) as that would require larger changes.

Add UCentralSchema and convert Modeler.DataModel.latestDeviceStatusRadios
